### ISSUE TITLE
Cloudflare Pass Can't be used.

### ISSUE THREAD

**Issue by zhiyan114** [privacypass/challenge-bypass-extension#163]
So today, I solved a Cloudflare Recaptcha via the get more pass section. When I did that, it registered the 30 tokens like it normally would but when I tried to spend them, the icon greyed out and showing that I don't have any tokens.

This is very likely a bug and anything I can do to solve it? The problem still occurs even after I cleared the token and solve another captcha.

**Comment by alxdavids** [comment]
Which version of the extension do you have? If you have 2.0.5 or older, then this may be related to #157. If you have 2.0.6, then this version should be working?

**Comment by zhiyan114** [comment]
Yes, it version 2.0.6, when I clear the token, I only receive 5 tokens instead of 30 so I re-enabled the extension and now I receive 30 passes but unable to once again spend them.

**Comment by zhiyan114** [comment]
Oops, my misunderstanding, it seems like both Cloudflare and Regular captcha token are separate and Cloudflare can only be used with Cloudflare sites. It then working as intended.

**Comment by zhiyan114** [comment]
Nevermind the issue seems still there. When I tried to solve a Cloudflare Captcha (i.e. https://captcha.website/), the token still won't be used.

**Comment by alxdavids** [comment]
This is intentional. https://captcha.website is only provided as a mechanism for *gaining* tokens issued by CF. Tokens may be spent on other CF websites that request the user to complete a CAPTCHA.
